# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            AfterStudy
tagline:          'AfterStudy, Korea Seoul'
description:      '서울대 입구역 TOZ 개발 스터디 모임'
url:              https://afterstudy.github.io
baseurl:          /

author:
  name:           'AfterStudy'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AfterStudy/AfterStudy.github.io
